// <auto-generated />
using System;
using DevBol.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevBol.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20241231161315_Uf_relacao_Uf_Equipe")]
    partial class Uf_relacao_Uf_Equipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumRodadas")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Escudo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumJogos")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRodada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Rodadas", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Ufs.Uf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Ufs", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Equipes.Equipe", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Ufs.Uf", "Uf")
                        .WithMany("Equipes")
                        .HasForeignKey("UfId");

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("Rodadas")
                        .HasForeignKey("CampeonatoId")
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.Campeonato", b =>
                {
                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Ufs.Uf", b =>
                {
                    b.Navigation("Equipes");
                });
#pragma warning restore 612, 618
        }
    }
}
