// <auto-generated />
using System;
using DevBol.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevBol.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20250113220131_Ajuste_chaves")]
    partial class Ajuste_chaves
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevBol.Domain.Models.Apostadores.Apostador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApostadorCampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorCampeonatoId");

                    b.ToTable("Apostadores", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Apostas.Aposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostadorCampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraAposta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enviada")
                        .HasColumnType("bit");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlacarApostaCasa")
                        .HasColumnType("int");

                    b.Property<int>("PlacarApostaVisita")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorCampeonatoId");

                    b.HasIndex("JogoId");

                    b.ToTable("Apostas", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.ApostadorCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApostadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorId");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("ApostadoresCampeonatos", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumRodadas")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.EquipeCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("EquipeId");

                    b.ToTable("EquipesCampeonatos", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Escudo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Sigla")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Estadios.Estadio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Estadios", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Jogos.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeCasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HoraJogo")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlacarCasa")
                        .HasColumnType("int");

                    b.Property<int>("PlacarVisita")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipeCasaId");

                    b.HasIndex("EquipeVisitanteId");

                    b.HasIndex("EstadioId");

                    b.HasIndex("RodadaId");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumJogos")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRodada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Rodadas", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Ufs.Uf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Ufs", (string)null);
                });

            modelBuilder.Entity("DevBol.Domain.Models.Apostadores.Apostador", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Campeonatos.ApostadorCampeonato", null)
                        .WithMany("Apostadores")
                        .HasForeignKey("ApostadorCampeonatoId");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Apostas.Aposta", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Campeonatos.ApostadorCampeonato", "ApostadorCampeonato")
                        .WithMany("Apostas")
                        .HasForeignKey("ApostadorCampeonatoId")
                        .IsRequired();

                    b.HasOne("DevBol.Domain.Models.Jogos.Jogo", "Jogo")
                        .WithMany("Apostas")
                        .HasForeignKey("JogoId")
                        .IsRequired();

                    b.Navigation("ApostadorCampeonato");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.ApostadorCampeonato", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Apostadores.Apostador", "Apostador")
                        .WithMany("ApostadoresCampeonatos")
                        .HasForeignKey("ApostadorId")
                        .IsRequired();

                    b.HasOne("DevBol.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("ApostadoresCampeonatos")
                        .HasForeignKey("CampeonatoId")
                        .IsRequired();

                    b.Navigation("Apostador");

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.EquipeCampeonato", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("EquipesCampeonatos")
                        .HasForeignKey("CampeonatoId")
                        .IsRequired();

                    b.HasOne("DevBol.Domain.Models.Equipes.Equipe", "Equipe")
                        .WithMany("EquipesCampeonatos")
                        .HasForeignKey("EquipeId")
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Equipes.Equipe", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Ufs.Uf", "Uf")
                        .WithMany("Equipes")
                        .HasForeignKey("UfId");

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Estadios.Estadio", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Ufs.Uf", "Uf")
                        .WithMany("Estadios")
                        .HasForeignKey("UfId");

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Jogos.Jogo", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Campeonatos.EquipeCampeonato", "EquipeCasa")
                        .WithMany("JogosCasa")
                        .HasForeignKey("EquipeCasaId")
                        .IsRequired();

                    b.HasOne("DevBol.Domain.Models.Campeonatos.EquipeCampeonato", "EquipeVisitante")
                        .WithMany("JogosVisitante")
                        .HasForeignKey("EquipeVisitanteId")
                        .IsRequired();

                    b.HasOne("DevBol.Domain.Models.Estadios.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId")
                        .IsRequired();

                    b.HasOne("DevBol.Domain.Models.Rodadas.Rodada", "Rodada")
                        .WithMany("JogosRodada")
                        .HasForeignKey("RodadaId")
                        .IsRequired();

                    b.Navigation("EquipeCasa");

                    b.Navigation("EquipeVisitante");

                    b.Navigation("Estadio");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.HasOne("DevBol.Domain.Models.Campeonatos.Campeonato", "Campeonato")
                        .WithMany("Rodadas")
                        .HasForeignKey("CampeonatoId")
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Apostadores.Apostador", b =>
                {
                    b.Navigation("ApostadoresCampeonatos");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.ApostadorCampeonato", b =>
                {
                    b.Navigation("Apostadores");

                    b.Navigation("Apostas");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.Campeonato", b =>
                {
                    b.Navigation("ApostadoresCampeonatos");

                    b.Navigation("EquipesCampeonatos");

                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Campeonatos.EquipeCampeonato", b =>
                {
                    b.Navigation("JogosCasa");

                    b.Navigation("JogosVisitante");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Equipes.Equipe", b =>
                {
                    b.Navigation("EquipesCampeonatos");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Jogos.Jogo", b =>
                {
                    b.Navigation("Apostas");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Rodadas.Rodada", b =>
                {
                    b.Navigation("JogosRodada");
                });

            modelBuilder.Entity("DevBol.Domain.Models.Ufs.Uf", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Estadios");
                });
#pragma warning restore 612, 618
        }
    }
}
